name: Barford Driveways
favicon: null
layout_spectrum: 0.75411
typography_spectrum: 0.65481
title: Greener Driveways
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a5003a'
    - '#028e13'
    - '#784503'
    - '#a17f52'
  brandStrength: 0.8540780553594232
  lightness: 0.25
  saturation: 0.6605787484440953
  rhythmicContrast: 0.7194430010858923
purpose: []
