name: Barford Driveways
favicon: null
layout_spectrum: 0.8187897396273911
typography_spectrum: 0.8284298388753086
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8540780553594232
  lightness: 0.5596472537145019
  saturation: 0.6605787484440953
  rhythmicContrast: 0.7194430010858923
purpose: []
